---
- hosts: 127.0.0.1
  connection: local
  vars:
    user: root
  tasks:
  - name: ensure that port 80 is closed
    action: shell HTTP_RULE_NO=$(iptables -L INPUT --line-numbers | grep 'http' | awk '{print $1}'); iptables -D INPUT $HTTP_RULE_NO
  - name: Save updated iptable rules
    action: command /sbin/service iptables save